name: Build release
on:  
  release:
    types: [created]
jobs:
  static:
    name: Create static release artifact
    runs-on: ubuntu-latest
    container:
      image: alpine:3.13
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          apk add alpine-sdk

      - name: Build release
        run: |
          make static

          version=$(grep CPUBENCH_VERSION cpubench.h | awk '{ print $3 }' | sed s/'"'//g)
          cp grid-cpubench-simple grid-cpubench-simple-${version}-linux-amd64-static

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'grid-cpubench-simple-*-linux-amd64-static'

